# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7465051044a52db96c45a2b3fce208c2a35049342c198bb53b7feb0fad4f74085ba5f283aeebf3f7cd8d030218b1eb66d2634a770d8398fd4c8668a44a28617

test:
  secret_key_base: 5db576a7584a5bcb7e289fee56b5e3612a521ba2bcf14821de8d1ecfe578c8563e706e64bef9eba0596efe3757620fe4e586ab9f1e5d23ad6fba08088593459a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
